/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWeeklyRouteImport } from './routes/app.weekly'
import { Route as AppResumeRouteImport } from './routes/app.resume'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppIntervuRouteImport } from './routes/app.intervu'
import { Route as AppHrRouteImport } from './routes/app.hr'
import { Route as AppEnglishCoachRouteImport } from './routes/app.english-coach'
import { Route as AppDoubtAssistantRouteImport } from './routes/app.doubt-assistant'
import { Route as AppDailyRouteImport } from './routes/app.daily'
import { Route as AppConversationPracticeRouteImport } from './routes/app.conversation-practice'
import { Route as AppCodingRouteImport } from './routes/app.coding'
import { Route as AppAptitudeRouteImport } from './routes/app.aptitude'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAchievementsRouteImport } from './routes/app.achievements'
import { Route as AppCodingSolveRouteImport } from './routes/app.coding.solve'
import { Route as AppCodingInstructionsRouteImport } from './routes/app.coding.instructions'
import { Route as AppAptitudeTestRouteImport } from './routes/app.aptitude.test'
import { Route as AppAptitudeResultsRouteImport } from './routes/app.aptitude.results'
import { Route as AppAptitudeInstructionsRouteImport } from './routes/app.aptitude.instructions'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWeeklyRoute = AppWeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => AppRoute,
} as any)
const AppResumeRoute = AppResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppIntervuRoute = AppIntervuRouteImport.update({
  id: '/intervu',
  path: '/intervu',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppEnglishCoachRoute = AppEnglishCoachRouteImport.update({
  id: '/english-coach',
  path: '/english-coach',
  getParentRoute: () => AppRoute,
} as any)
const AppDoubtAssistantRoute = AppDoubtAssistantRouteImport.update({
  id: '/doubt-assistant',
  path: '/doubt-assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppDailyRoute = AppDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationPracticeRoute = AppConversationPracticeRouteImport.update({
  id: '/conversation-practice',
  path: '/conversation-practice',
  getParentRoute: () => AppRoute,
} as any)
const AppCodingRoute = AppCodingRouteImport.update({
  id: '/coding',
  path: '/coding',
  getParentRoute: () => AppRoute,
} as any)
const AppAptitudeRoute = AppAptitudeRouteImport.update({
  id: '/aptitude',
  path: '/aptitude',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppCodingSolveRoute = AppCodingSolveRouteImport.update({
  id: '/solve',
  path: '/solve',
  getParentRoute: () => AppCodingRoute,
} as any)
const AppCodingInstructionsRoute = AppCodingInstructionsRouteImport.update({
  id: '/instructions',
  path: '/instructions',
  getParentRoute: () => AppCodingRoute,
} as any)
const AppAptitudeTestRoute = AppAptitudeTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AppAptitudeRoute,
} as any)
const AppAptitudeResultsRoute = AppAptitudeResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppAptitudeRoute,
} as any)
const AppAptitudeInstructionsRoute = AppAptitudeInstructionsRouteImport.update({
  id: '/instructions',
  path: '/instructions',
  getParentRoute: () => AppAptitudeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/aptitude': typeof AppAptitudeRouteWithChildren
  '/app/coding': typeof AppCodingRouteWithChildren
  '/app/conversation-practice': typeof AppConversationPracticeRoute
  '/app/daily': typeof AppDailyRoute
  '/app/doubt-assistant': typeof AppDoubtAssistantRoute
  '/app/english-coach': typeof AppEnglishCoachRoute
  '/app/hr': typeof AppHrRoute
  '/app/intervu': typeof AppIntervuRoute
  '/app/profile': typeof AppProfileRoute
  '/app/resume': typeof AppResumeRoute
  '/app/weekly': typeof AppWeeklyRoute
  '/app/': typeof AppIndexRoute
  '/app/aptitude/instructions': typeof AppAptitudeInstructionsRoute
  '/app/aptitude/results': typeof AppAptitudeResultsRoute
  '/app/aptitude/test': typeof AppAptitudeTestRoute
  '/app/coding/instructions': typeof AppCodingInstructionsRoute
  '/app/coding/solve': typeof AppCodingSolveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/aptitude': typeof AppAptitudeRouteWithChildren
  '/app/coding': typeof AppCodingRouteWithChildren
  '/app/conversation-practice': typeof AppConversationPracticeRoute
  '/app/daily': typeof AppDailyRoute
  '/app/doubt-assistant': typeof AppDoubtAssistantRoute
  '/app/english-coach': typeof AppEnglishCoachRoute
  '/app/hr': typeof AppHrRoute
  '/app/intervu': typeof AppIntervuRoute
  '/app/profile': typeof AppProfileRoute
  '/app/resume': typeof AppResumeRoute
  '/app/weekly': typeof AppWeeklyRoute
  '/app': typeof AppIndexRoute
  '/app/aptitude/instructions': typeof AppAptitudeInstructionsRoute
  '/app/aptitude/results': typeof AppAptitudeResultsRoute
  '/app/aptitude/test': typeof AppAptitudeTestRoute
  '/app/coding/instructions': typeof AppCodingInstructionsRoute
  '/app/coding/solve': typeof AppCodingSolveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/aptitude': typeof AppAptitudeRouteWithChildren
  '/app/coding': typeof AppCodingRouteWithChildren
  '/app/conversation-practice': typeof AppConversationPracticeRoute
  '/app/daily': typeof AppDailyRoute
  '/app/doubt-assistant': typeof AppDoubtAssistantRoute
  '/app/english-coach': typeof AppEnglishCoachRoute
  '/app/hr': typeof AppHrRoute
  '/app/intervu': typeof AppIntervuRoute
  '/app/profile': typeof AppProfileRoute
  '/app/resume': typeof AppResumeRoute
  '/app/weekly': typeof AppWeeklyRoute
  '/app/': typeof AppIndexRoute
  '/app/aptitude/instructions': typeof AppAptitudeInstructionsRoute
  '/app/aptitude/results': typeof AppAptitudeResultsRoute
  '/app/aptitude/test': typeof AppAptitudeTestRoute
  '/app/coding/instructions': typeof AppCodingInstructionsRoute
  '/app/coding/solve': typeof AppCodingSolveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/achievements'
    | '/app/analytics'
    | '/app/aptitude'
    | '/app/coding'
    | '/app/conversation-practice'
    | '/app/daily'
    | '/app/doubt-assistant'
    | '/app/english-coach'
    | '/app/hr'
    | '/app/intervu'
    | '/app/profile'
    | '/app/resume'
    | '/app/weekly'
    | '/app/'
    | '/app/aptitude/instructions'
    | '/app/aptitude/results'
    | '/app/aptitude/test'
    | '/app/coding/instructions'
    | '/app/coding/solve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/achievements'
    | '/app/analytics'
    | '/app/aptitude'
    | '/app/coding'
    | '/app/conversation-practice'
    | '/app/daily'
    | '/app/doubt-assistant'
    | '/app/english-coach'
    | '/app/hr'
    | '/app/intervu'
    | '/app/profile'
    | '/app/resume'
    | '/app/weekly'
    | '/app'
    | '/app/aptitude/instructions'
    | '/app/aptitude/results'
    | '/app/aptitude/test'
    | '/app/coding/instructions'
    | '/app/coding/solve'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/achievements'
    | '/app/analytics'
    | '/app/aptitude'
    | '/app/coding'
    | '/app/conversation-practice'
    | '/app/daily'
    | '/app/doubt-assistant'
    | '/app/english-coach'
    | '/app/hr'
    | '/app/intervu'
    | '/app/profile'
    | '/app/resume'
    | '/app/weekly'
    | '/app/'
    | '/app/aptitude/instructions'
    | '/app/aptitude/results'
    | '/app/aptitude/test'
    | '/app/coding/instructions'
    | '/app/coding/solve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/weekly': {
      id: '/app/weekly'
      path: '/weekly'
      fullPath: '/app/weekly'
      preLoaderRoute: typeof AppWeeklyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resume': {
      id: '/app/resume'
      path: '/resume'
      fullPath: '/app/resume'
      preLoaderRoute: typeof AppResumeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/intervu': {
      id: '/app/intervu'
      path: '/intervu'
      fullPath: '/app/intervu'
      preLoaderRoute: typeof AppIntervuRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hr': {
      id: '/app/hr'
      path: '/hr'
      fullPath: '/app/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/english-coach': {
      id: '/app/english-coach'
      path: '/english-coach'
      fullPath: '/app/english-coach'
      preLoaderRoute: typeof AppEnglishCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/doubt-assistant': {
      id: '/app/doubt-assistant'
      path: '/doubt-assistant'
      fullPath: '/app/doubt-assistant'
      preLoaderRoute: typeof AppDoubtAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/daily': {
      id: '/app/daily'
      path: '/daily'
      fullPath: '/app/daily'
      preLoaderRoute: typeof AppDailyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conversation-practice': {
      id: '/app/conversation-practice'
      path: '/conversation-practice'
      fullPath: '/app/conversation-practice'
      preLoaderRoute: typeof AppConversationPracticeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coding': {
      id: '/app/coding'
      path: '/coding'
      fullPath: '/app/coding'
      preLoaderRoute: typeof AppCodingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/aptitude': {
      id: '/app/aptitude'
      path: '/aptitude'
      fullPath: '/app/aptitude'
      preLoaderRoute: typeof AppAptitudeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coding/solve': {
      id: '/app/coding/solve'
      path: '/solve'
      fullPath: '/app/coding/solve'
      preLoaderRoute: typeof AppCodingSolveRouteImport
      parentRoute: typeof AppCodingRoute
    }
    '/app/coding/instructions': {
      id: '/app/coding/instructions'
      path: '/instructions'
      fullPath: '/app/coding/instructions'
      preLoaderRoute: typeof AppCodingInstructionsRouteImport
      parentRoute: typeof AppCodingRoute
    }
    '/app/aptitude/test': {
      id: '/app/aptitude/test'
      path: '/test'
      fullPath: '/app/aptitude/test'
      preLoaderRoute: typeof AppAptitudeTestRouteImport
      parentRoute: typeof AppAptitudeRoute
    }
    '/app/aptitude/results': {
      id: '/app/aptitude/results'
      path: '/results'
      fullPath: '/app/aptitude/results'
      preLoaderRoute: typeof AppAptitudeResultsRouteImport
      parentRoute: typeof AppAptitudeRoute
    }
    '/app/aptitude/instructions': {
      id: '/app/aptitude/instructions'
      path: '/instructions'
      fullPath: '/app/aptitude/instructions'
      preLoaderRoute: typeof AppAptitudeInstructionsRouteImport
      parentRoute: typeof AppAptitudeRoute
    }
  }
}

interface AppAptitudeRouteChildren {
  AppAptitudeInstructionsRoute: typeof AppAptitudeInstructionsRoute
  AppAptitudeResultsRoute: typeof AppAptitudeResultsRoute
  AppAptitudeTestRoute: typeof AppAptitudeTestRoute
}

const AppAptitudeRouteChildren: AppAptitudeRouteChildren = {
  AppAptitudeInstructionsRoute: AppAptitudeInstructionsRoute,
  AppAptitudeResultsRoute: AppAptitudeResultsRoute,
  AppAptitudeTestRoute: AppAptitudeTestRoute,
}

const AppAptitudeRouteWithChildren = AppAptitudeRoute._addFileChildren(
  AppAptitudeRouteChildren,
)

interface AppCodingRouteChildren {
  AppCodingInstructionsRoute: typeof AppCodingInstructionsRoute
  AppCodingSolveRoute: typeof AppCodingSolveRoute
}

const AppCodingRouteChildren: AppCodingRouteChildren = {
  AppCodingInstructionsRoute: AppCodingInstructionsRoute,
  AppCodingSolveRoute: AppCodingSolveRoute,
}

const AppCodingRouteWithChildren = AppCodingRoute._addFileChildren(
  AppCodingRouteChildren,
)

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAptitudeRoute: typeof AppAptitudeRouteWithChildren
  AppCodingRoute: typeof AppCodingRouteWithChildren
  AppConversationPracticeRoute: typeof AppConversationPracticeRoute
  AppDailyRoute: typeof AppDailyRoute
  AppDoubtAssistantRoute: typeof AppDoubtAssistantRoute
  AppEnglishCoachRoute: typeof AppEnglishCoachRoute
  AppHrRoute: typeof AppHrRoute
  AppIntervuRoute: typeof AppIntervuRoute
  AppProfileRoute: typeof AppProfileRoute
  AppResumeRoute: typeof AppResumeRoute
  AppWeeklyRoute: typeof AppWeeklyRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAptitudeRoute: AppAptitudeRouteWithChildren,
  AppCodingRoute: AppCodingRouteWithChildren,
  AppConversationPracticeRoute: AppConversationPracticeRoute,
  AppDailyRoute: AppDailyRoute,
  AppDoubtAssistantRoute: AppDoubtAssistantRoute,
  AppEnglishCoachRoute: AppEnglishCoachRoute,
  AppHrRoute: AppHrRoute,
  AppIntervuRoute: AppIntervuRoute,
  AppProfileRoute: AppProfileRoute,
  AppResumeRoute: AppResumeRoute,
  AppWeeklyRoute: AppWeeklyRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
